apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udacity-cd-03-project-feedservice
  name: udacity-cd-03-project-feedservice
spec:
  replicas: 3
  selector:
    matchLabels:
      service: udacity-cd-03-project-feedservice
  template:
    metadata:
      labels:
        service: udacity-cd-03-project-feedservice
    spec:
      containers:
        - image: hnrchrdl/udacity-cd-03-project-feedservice
          name: udacity-cd-03-project-feedservice
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: JWT_SECRET
            - name: POSTGRESS_DB
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: POSTGRESS_DB
            - name: POSTGRESS_HOST
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: POSTGRESS_HOST
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udacity-03-project-env-secret
                  key: POSTGRESS_PASSWORD
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udacity-03-project-env-secret
                  key: POSTGRESS_USERNAME
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
