apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udacity-cd-03-project-userservice
  name: udacity-cd-03-project-userservice
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udacity-cd-03-project-userservice
  template:
    metadata:
      labels:
        service: udacity-cd-03-project-userservice
    spec:
      containers:
        - image: hnrchrdl/udacity-cd-03-project-userservice
          name: udacity-cd-03-project-userservice
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: JWT_SECRET
            - name: POSTGRESS_DB
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: POSTGRESS_DB
            - name: POSTGRESS_HOST
              valueFrom:
                configMapKeyRef:
                  name: udacity-03-project-config-map
                  key: POSTGRESS_HOST
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udacity-03-project-env-secret
                  key: POSTGRESS_PASSWORD
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udacity-03-project-env-secret
                  key: POSTGRESS_USERNAME
      restartPolicy: Always
