apiVersion: v1
kind: Service
metadata:
  labels:
    service: udacity-cd-03-project-feedservice
  name: udacity-cd-03-project-feedservice
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: udacity-cd-03-project-feedservice
