apiVersion: v1
kind: Service
metadata:
  labels:
    service: udacity-cd-03-project-frontend
  name: udacity-cd-03-project-frontend
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
  selector:
    service: udacity-cd-03-project-frontend
  type: LoadBalancer
