apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udacity-cd-03-project-frontend
  name: udacity-cd-03-project-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udacity-cd-03-project-frontend
  template:
    metadata:
      labels:
        service: udacity-cd-03-project-frontend
        api: external
    spec:
      containers:
        - image: hnrchrdl/udacity-cd-03-project-frontend
          name: udacity-cd-03-project-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always
